<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="idk_vacuum">

    <xacro:macro name="tube" params="prefix name diameter length">
        <link name="${prefix}${name}">
            <!-- <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial> -->
            <visual name="">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${diameter/2}" length="${length}"/>
                </geometry>
                <material name="">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${diameter/2}" length="${length}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

</robot>